### ISSUE TITLE
Create an EFS

### ISSUE THREAD

**Issue by hsy3418** [devopsacademyau/2020-feb-project1-group3#17]
**Task definitions** 
 - use vpc from network stack
  - at least one mount target (AZ)
  - security group allowing only ECS instances to access it
  - no lifecycle policy
  - throughput mode bursting
  - performance mode general purpose
  - no need for encryption
  - no need for IAM authentication
  - add one access point:
    - name wordpress
    - path /wordpress

**DOD:**

  - efs is available in at least one AZ
  - I can mount efs volume on an ec2 instance running on private subnet following instructions https://docs.aws.amazon.com/efs/latest/ug/mounting-fs.html
  - I CAN’T mount efs volume from instance on public subnet

**Comment by caiocezart** [comment]
- Please update encryption to true (it doesn't require further configuration)
- add efs security ground with ingress tcp 2049 from security group id of ecs cluster nodes (input variable)
